/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import auxiliar.Senhas;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class AlteraInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AlteraInfo
     */
    
    private Universidade uniPrincipal;
    private String label;
    private String self;
    private int tipo;
    private String senha;
    private Senhas infoLogin;
    
    public AlteraInfo(Universidade uniPrincipal, Senhas infoLogin, String label, String self, int tipo) {
        initComponents();
        this.uniPrincipal = uniPrincipal;
        this.label = label;
        this.self = self;
        this.tipo = tipo;
        this.infoLogin = infoLogin;
        this.senha = infoLogin.getSenha(self);
        
        labelInfo.setText(label);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInfo = new javax.swing.JLabel();
        textInfo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textSenha = new javax.swing.JTextField();
        bConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        labelInfo.setText("Info:");

        jLabel2.setText("Senha Atual");

        bConfirmar.setText("Confirmar");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bConfirmar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textSenha))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelInfo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        String info = "0";
        try{
            if(senha.equals(textSenha.getText())){

                if(tipo == 1){
                    if(label.equals("Email")){
                        System.out.println("ENTROU");
                        uniPrincipal.getSecretario(self).setEmail(textInfo.getText());
                        System.out.println("ENTROU");
                    }
                    else if(label.equals("Numero")){
                        uniPrincipal.getSecretario(self).setNumeroContato(textInfo.getText());
                    }
                    else if(label.equals("Nova Senha")){
                        infoLogin.alteraSenha(self, textInfo.getText());
                    }
                    info = uniPrincipal.getSecretarioUniversidade(self);
                }
                else if(tipo == 2){
                    if(label.equals("Email")){
                        uniPrincipal.getProfessor(self).setEmail(textInfo.getText());
                    }
                    else if(label.equals("Numero")){
                        uniPrincipal.getProfessor(self).setNumeroContato(textInfo.getText());
                    }
                    else if(label.equals("Nova Senha")){
                        infoLogin.alteraSenha(self, textInfo.getText());
                    }

                    info = uniPrincipal.getProfessorUniversidade(self);
                }
                else if(tipo == 3){
                    if(label.equals("Email")){
                        uniPrincipal.getAluno(self).setEmail(textInfo.getText());
                    }
                    else if(label.equals("Numero")){
                        uniPrincipal.getAluno(self).setNumeroContato(textInfo.getText());
                    }
                    else if(label.equals("Nova Senha")){
                        infoLogin.alteraSenha(self, textInfo.getText());
                    }

                    info = uniPrincipal.getAlunoUniversidade(self);
                }
                textArea.setText(info);
            }
            else{
                JOptionPane.showMessageDialog(null, "Senha Incorreta", "ERRO", ERROR_MESSAGE);
            }
        }
        catch(NullPointerException nullPointerException){
            JOptionPane.showMessageDialog(null, "Erro ao Carregar Informações", "ERRO", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConfirmar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textInfo;
    private javax.swing.JTextField textSenha;
    // End of variables declaration//GEN-END:variables
}
