/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import menu.MenuSecretaria;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class BurcaString extends javax.swing.JInternalFrame {

    /**
     * Creates new form BurcaString
     */
    private Universidade uniPrincipal;
    private int tipo;
    
    public BurcaString(Universidade uniPrincipal, int tipo, String self) {
        initComponents();
        String info = "0";
        if(tipo == 1){
            info = uniPrincipal.getSecretarioUniversidade(self);
        }
        else if(tipo == 2){
            info = uniPrincipal.getProfessorUniversidade(self);
        }
        else if(tipo == 3){
            info = uniPrincipal.getAlunoUniversidade(self);
            jLabel1.setText("Matricula:");
        }
        textBusca.setText(self);
        jTextArea1.setText(info);
    }
    
    public BurcaString(Universidade uniPrincipal, int tipo) {
        initComponents();
        this.uniPrincipal = uniPrincipal;
        this.tipo = tipo;
        if(tipo == 3)
            jLabel1.setText("Matricula:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textBusca = new javax.swing.JTextField();
        bConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Registro:");

        bConfirmar.setText("Confirmar");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(bConfirmar)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textBusca)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(bConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        String info = "0";
        if(tipo == 1){
            info = uniPrincipal.getSecretarioUniversidade(textBusca.getText());
        }
        else if(tipo == 2){
            info = uniPrincipal.getProfessorUniversidade(textBusca.getText());
        }
        else if(tipo == 3){
            info = uniPrincipal.getAlunoUniversidade(textBusca.getText());
        }
        jTextArea1.setText(info);
    }//GEN-LAST:event_bConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textBusca;
    // End of variables declaration//GEN-END:variables
}
