/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import trabalho2.Aluno;
import trabalho2.Curso;
import trabalho2.Departamento;
import trabalho2.Materia;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class CursoInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form DepListProf
     */
    
    private Universidade uniPrincipal;
    private Departamento depPrincipal;
    private Curso cursoPrincipal;
    
    public CursoInfo(Universidade uniPrincipal) {
        initComponents();
        this.uniPrincipal = uniPrincipal;
        ArrayList<Departamento> depList = uniPrincipal.getDepList();
        for(int i = 0; i < depList.size(); i++){
                comboBoxDep.addItem(depList.get(i).getCodDep());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxDep = new javax.swing.JComboBox<>();
        labelDepShow = new javax.swing.JLabel();
        bInformacoes = new javax.swing.JButton();
        bMaterias = new javax.swing.JButton();
        comboBoxCurso = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        labelCursoShow = new javax.swing.JLabel();
        bAluno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        jLabel2.setText("jLabel2");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Departamento:");

        comboBoxDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento" }));
        comboBoxDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDepActionPerformed(evt);
            }
        });

        labelDepShow.setText("Nome");

        bInformacoes.setText("Informações");
        bInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInformacoesActionPerformed(evt);
            }
        });

        bMaterias.setText("Matérias");
        bMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMateriasActionPerformed(evt);
            }
        });

        comboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Curso" }));
        comboBoxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCursoActionPerformed(evt);
            }
        });

        jLabel3.setText("Curso:");

        labelCursoShow.setText("Nome");

        bAluno.setText("Alunos");
        bAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelCursoShow)
                                        .addGap(175, 175, 175))
                                    .addComponent(comboBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bInformacoes)
                                .addGap(18, 18, 18)
                                .addComponent(bMaterias)
                                .addGap(18, 18, 18)
                                .addComponent(bAluno))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDepShow)
                            .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDepShow)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCursoShow)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bInformacoes)
                    .addComponent(bMaterias)
                    .addComponent(bAluno))
                .addGap(22, 22, 22))
        );

        text.setEditable(false);
        text.setColumns(20);
        text.setRows(5);
        jScrollPane2.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDepActionPerformed
        try{
            String cod = String.valueOf(comboBoxDep.getSelectedItem());
            labelDepShow.setText(uniPrincipal.getDepartamento(cod).getNome());
            this.depPrincipal = uniPrincipal.getDepartamento(cod);
            
            comboBoxCurso.removeAllItems();
            comboBoxCurso.addItem("Curso");

            
            ArrayList<Curso> cursoList = this.depPrincipal.getCursoList();
            for(int i = 0; i < cursoList.size(); i++){
                    comboBoxCurso.addItem(cursoList.get(i).getCodCurso());
            }
        }
        catch(NullPointerException nullPointerException){
            labelDepShow.setText("Nome");
            this.depPrincipal = null;
            comboBoxCurso.removeAllItems();
            comboBoxCurso.addItem("Curso");
        }

    }//GEN-LAST:event_comboBoxDepActionPerformed

    private void bInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInformacoesActionPerformed
        text.setText(cursoPrincipal.toString());
    }//GEN-LAST:event_bInformacoesActionPerformed

    private void bMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMateriasActionPerformed
        try{
            ArrayList<Materia> matList = cursoPrincipal.getMatList();
            String cursoText = "";

            for(int i = 0; i < matList.size(); i++){
                cursoText = cursoText + matList.get(i).getNome() + "\n";
            }

            text.setText(cursoText);
        }
        catch(NullPointerException nullPointerException){
            JOptionPane.showMessageDialog(null, "Não existem Cursos cadastrados", "ERRO", ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bMateriasActionPerformed

    private void comboBoxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCursoActionPerformed
        try{     
            String cod = String.valueOf(comboBoxCurso.getSelectedItem());
            labelCursoShow.setText(depPrincipal.getCurso(cod).getNome());
            this.cursoPrincipal = depPrincipal.getCurso(cod);
       }
       catch(NullPointerException nullPointerException){
            labelCursoShow.setText("Nome");
            this.cursoPrincipal = null;
       }
    }//GEN-LAST:event_comboBoxCursoActionPerformed

    private void bAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlunoActionPerformed
        try{
            ArrayList<Aluno> alunoList = cursoPrincipal.getAlunoList();
            String cursoText = "";

            for(int i = 0; i < alunoList.size(); i++){
                cursoText = cursoText + alunoList.get(i).getNome() + "\n";
            }

            text.setText(cursoText);
        }
        catch(NullPointerException nullPointerException){
            JOptionPane.showMessageDialog(null, "Não existem Cursos cadastrados", "ERRO", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAluno;
    private javax.swing.JButton bInformacoes;
    private javax.swing.JButton bMaterias;
    private javax.swing.JComboBox<String> comboBoxCurso;
    private javax.swing.JComboBox<String> comboBoxDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCursoShow;
    private javax.swing.JLabel labelDepShow;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
