/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import trabalho2.Curso;
import trabalho2.Departamento;
import trabalho2.Professor;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class DepInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form DepListProf
     */
    
    private Universidade uniPrincipal;
    private Departamento depPrincipal;
    
    public DepInfo(Universidade uniPrincipal) {
        initComponents();
        this.uniPrincipal = uniPrincipal;
        ArrayList<Departamento> depList = uniPrincipal.getDepList();
        for(int i = 0; i < depList.size(); i++){
                comboBoxDep.addItem(depList.get(i).getCodDep());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxDep = new javax.swing.JComboBox<>();
        labelDepShow = new javax.swing.JLabel();
        informacoes = new javax.swing.JButton();
        cursos = new javax.swing.JButton();
        professores = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Departamento:");

        comboBoxDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento" }));
        comboBoxDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDepActionPerformed(evt);
            }
        });

        labelDepShow.setText("Nome");

        informacoes.setText("Informações");
        informacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacoesActionPerformed(evt);
            }
        });

        cursos.setText("Cursos");
        cursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursosActionPerformed(evt);
            }
        });

        professores.setText("Professores");
        professores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDepShow)
                            .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addComponent(informacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cursos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(professores)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDepShow)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(informacoes)
                    .addComponent(cursos)
                    .addComponent(professores))
                .addContainerGap())
        );

        text.setEditable(false);
        text.setColumns(20);
        text.setRows(5);
        jScrollPane2.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDepActionPerformed
        try{     
            String cod = String.valueOf(comboBoxDep.getSelectedItem());
            labelDepShow.setText(uniPrincipal.getDepartamento(cod).getNome());
            this.depPrincipal = uniPrincipal.getDepartamento(cod);
            
       }
       catch(NullPointerException nullPointerException){
            labelDepShow.setText("Nome");
            this.depPrincipal = null;
       }
    }//GEN-LAST:event_comboBoxDepActionPerformed

    private void informacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacoesActionPerformed
        text.setText(depPrincipal.toString());
    }//GEN-LAST:event_informacoesActionPerformed

    private void cursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursosActionPerformed
        try{
            ArrayList<Curso> cursoList = depPrincipal.getCursoList();
            String cursoText = "";

            for(int i = 0; i < cursoList.size(); i++){
                cursoText = cursoText + cursoList.get(i).getNome() + "\n";
            }

            text.setText(cursoText);
        }
        catch(NullPointerException nullPointerException){
            JOptionPane.showMessageDialog(null, "Não existem Cursos cadastrados", "ERRO", ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_cursosActionPerformed

    private void professoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professoresActionPerformed
        try{
            ArrayList<Professor> profList = depPrincipal.getProfList();
            String profText = "";

            for(int i = 0; i < profList.size(); i++){
                profText = profText + profList.get(i).getNome() + "\n";
            }

            text.setText(profText);
        }
        catch(NullPointerException nullPointerException){
            JOptionPane.showMessageDialog(null, "Não existem Professores cadastrados", "ERRO", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_professoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDep;
    private javax.swing.JButton cursos;
    private javax.swing.JButton informacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDepShow;
    private javax.swing.JButton professores;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
