/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import auxiliar.Matricula;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import menu.MenuSecretaria;
import trabalho2.Aluno;
import trabalho2.Curso;
import trabalho2.Departamento;
import trabalho2.Materia;
import trabalho2.Secretario;

/**
 *
 * @author delatorre
 */
public class LidarMatricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaMateria
     */
    private Departamento depPrincipal;
    private Curso cursoPrincipal;
    private Materia materiaPrincipal;
    private ArrayList<Matricula> matriculaList;
    
    public LidarMatricula() {
        initComponents();
        comboBoxDep.addItem("Departamento");
        ArrayList<Departamento> depList = MenuSecretaria.getUniversidade().getDepList();
        for(int i = 0; i < depList.size(); i++){
                comboBoxDep.addItem(depList.get(i).getCodDep());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMateria = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        comboBoxDep = new javax.swing.JComboBox<>();
        labelDep = new javax.swing.JLabel();
        labelCurso = new javax.swing.JLabel();
        comboBoxCurso = new javax.swing.JComboBox<>();
        labelMateria = new javax.swing.JLabel();
        comboBoxMateria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bAceitar = new javax.swing.JButton();
        bRejeitar = new javax.swing.JButton();
        comboBoxAluno = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAluno = new javax.swing.JTextArea();

        jButton1.setText("jButton1");

        jLabel4.setText("jLabel4");

        setClosable(true);
        setIconifiable(true);

        textMateria.setEditable(false);
        textMateria.setColumns(20);
        textMateria.setRows(5);
        jScrollPane1.setViewportView(textMateria);

        comboBoxDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDepActionPerformed(evt);
            }
        });

        labelDep.setText("Nome");

        labelCurso.setText("Nome");

        comboBoxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCursoActionPerformed(evt);
            }
        });

        labelMateria.setText("Nome");

        comboBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMateriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Departamento:");

        jLabel2.setText("Curso:");

        jLabel3.setText("Materia:");

        bAceitar.setText("Aceitar");
        bAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceitarActionPerformed(evt);
            }
        });

        bRejeitar.setText("Rejeitar");
        bRejeitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRejeitarActionPerformed(evt);
            }
        });

        comboBoxAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAlunoActionPerformed(evt);
            }
        });

        jLabel5.setText("Aluno:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelMateria)
                            .addComponent(labelCurso)
                            .addComponent(labelDep)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bRejeitar)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxDep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboBoxMateria, 0, 131, Short.MAX_VALUE)))
                            .addComponent(comboBoxAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(bAceitar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDep, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceitar)
                    .addComponent(bRejeitar)))
        );

        textAluno.setEditable(false);
        textAluno.setColumns(20);
        textAluno.setRows(5);
        jScrollPane2.setViewportView(textAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDepActionPerformed
        try{
            String cod = String.valueOf(comboBoxDep.getSelectedItem());
            labelDep.setText(MenuSecretaria.getUniversidade().getDepartamento(cod).getNome());
            this.depPrincipal = MenuSecretaria.getUniversidade().getDepartamento(cod);

            comboBoxCurso.removeAllItems();
            comboBoxCurso.addItem("Curso");
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
            textMateria.setText("");
            
            ArrayList<Curso> cursoList = this.depPrincipal.getCursoList();
            for(int i = 0; i < cursoList.size(); i++){
                    comboBoxCurso.addItem(cursoList.get(i).getCodCurso());
            }
        }
        catch(NullPointerException nullPointerException){
            labelDep.setText("Departamento");
            this.depPrincipal = null;
            comboBoxCurso.removeAllItems();
            comboBoxCurso.addItem("Curso");
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
            textMateria.setText("");
            
        }
    }//GEN-LAST:event_comboBoxDepActionPerformed

    private void comboBoxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCursoActionPerformed
        try{     
            String cod = String.valueOf(comboBoxCurso.getSelectedItem());
            labelCurso.setText(depPrincipal.getCurso(cod).getNome());
            this.cursoPrincipal = depPrincipal.getCurso(cod);
            
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
            textMateria.setText("");
            
            ArrayList<Materia> matList = this.cursoPrincipal.getMatList();
            for(int i = 0; i < matList.size(); i++){
                    comboBoxMateria.addItem(matList.get(i).getCodMateria());
            }            
            
       }
       catch(NullPointerException nullPointerException){
            labelCurso.setText("Nome");
            this.cursoPrincipal = null;
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
            textMateria.setText("");
       }
    }//GEN-LAST:event_comboBoxCursoActionPerformed

    private void comboBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMateriaActionPerformed
        String nomeProfessor = "";
        try{     
            String cod = String.valueOf(comboBoxMateria.getSelectedItem());
            labelMateria.setText(cursoPrincipal.getMateria(cod).getNome());
            this.materiaPrincipal = cursoPrincipal.getMateria(cod);
            
            comboBoxAluno.removeAllItems();
            matriculaList = MenuSecretaria.getUniversidade().getSolicitacaoList();
            for(int i = 0; i < matriculaList.size(); i++){
                    if(matriculaList.get(i).getMateria().getCodMateria().equals(this.materiaPrincipal.getCodMateria())){
                        comboBoxAluno.addItem(matriculaList.get(i).getAluno().getMatricula());
                    }
            }  
        }
        catch(NullPointerException nullPointerException){
            labelMateria.setText("Nome");
            this.materiaPrincipal = null;
            textMateria.setText("");
       }
    }//GEN-LAST:event_comboBoxMateriaActionPerformed

    private void comboBoxAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAlunoActionPerformed
        try{
            textMateria.setText(this.materiaPrincipal.toString());
            String cod = String.valueOf(comboBoxAluno.getSelectedItem());
            textAluno.setText(MenuSecretaria.getUniversidade().getAlunoUniversidade(cod));
        }
        catch(NullPointerException nullPointerException){
            textMateria.setText("");
            textAluno.setText("");
       }
    }//GEN-LAST:event_comboBoxAlunoActionPerformed

    private void bAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceitarActionPerformed
        for(int i = 0; i < matriculaList.size(); i++){
            if(matriculaList.get(i).getMateria().getCodMateria().equals(this.materiaPrincipal.getCodMateria()) && matriculaList.get(i).getAluno().getMatricula().equals(String.valueOf(comboBoxAluno.getSelectedItem()))){
                matriculaList.get(i).aceitar();
                MenuSecretaria.getUniversidade().getAluno(String.valueOf(comboBoxAluno.getSelectedItem())).setMatriculaList(matriculaList.get(i));
                MenuSecretaria.getUniversidade().removeSolicitacao(this.materiaPrincipal.getCodMateria(), String.valueOf(comboBoxAluno.getSelectedItem()));
            }
        }  
        JOptionPane.showMessageDialog(null, "Matricula Aceita", "Salvo", INFORMATION_MESSAGE);
    }//GEN-LAST:event_bAceitarActionPerformed

    private void bRejeitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRejeitarActionPerformed
       for(int i = 0; i < matriculaList.size(); i++){
            if(matriculaList.get(i).getMateria().getCodMateria().equals(this.materiaPrincipal.getCodMateria()) && matriculaList.get(i).getAluno().getMatricula().equals(String.valueOf(comboBoxAluno.getSelectedItem()))){
                matriculaList.get(i).recusar();
                MenuSecretaria.getUniversidade().getAluno(String.valueOf(comboBoxAluno.getSelectedItem())).setMatriculaList(matriculaList.get(i));
                MenuSecretaria.getUniversidade().removeSolicitacao(this.materiaPrincipal.getCodMateria(), String.valueOf(comboBoxAluno.getSelectedItem()));
            }
        } 
       JOptionPane.showMessageDialog(null, "Matricula Rejeitada", "Salvo", INFORMATION_MESSAGE);
    }//GEN-LAST:event_bRejeitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceitar;
    private javax.swing.JButton bRejeitar;
    private javax.swing.JComboBox<String> comboBoxAluno;
    private javax.swing.JComboBox<String> comboBoxCurso;
    private javax.swing.JComboBox<String> comboBoxDep;
    private javax.swing.JComboBox<String> comboBoxMateria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelDep;
    private javax.swing.JLabel labelMateria;
    private javax.swing.JTextArea textAluno;
    private javax.swing.JTextArea textMateria;
    // End of variables declaration//GEN-END:variables
}
