/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import menu.MenuSecretaria;
import trabalho2.Aluno;
import trabalho2.Curso;
import trabalho2.Departamento;
import trabalho2.Materia;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class MateriaInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscaMateria
     */
    private Universidade uniPrincipal;
    private Departamento depPrincipal;
    private Curso cursoPrincipal;
    private Materia materiaPrincipal;
    
    public MateriaInfo(Universidade uniPrincipal) {
        initComponents();
        this.uniPrincipal = uniPrincipal;
        comboBoxDep.addItem("Departamento");
        ArrayList<Departamento> depList = uniPrincipal.getDepList();
        for(int i = 0; i < depList.size(); i++){
                comboBoxDep.addItem(depList.get(i).getCodDep());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textMateria = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        comboBoxDep = new javax.swing.JComboBox<>();
        labelDep = new javax.swing.JLabel();
        labelCurso = new javax.swing.JLabel();
        comboBoxCurso = new javax.swing.JComboBox<>();
        labelMateria = new javax.swing.JLabel();
        comboBoxMateria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bAlunos = new javax.swing.JButton();
        bProfessor = new javax.swing.JButton();
        bInfo = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        textMateria.setEditable(false);
        textMateria.setColumns(20);
        textMateria.setRows(5);
        jScrollPane1.setViewportView(textMateria);

        comboBoxDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDepActionPerformed(evt);
            }
        });

        labelDep.setText("Nome");

        labelCurso.setText("Nome");

        comboBoxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCursoActionPerformed(evt);
            }
        });

        labelMateria.setText("Nome");

        comboBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMateriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Departamento:");

        jLabel2.setText("Curso:");

        jLabel3.setText("Materia:");

        bAlunos.setText("Alunos");
        bAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlunosActionPerformed(evt);
            }
        });

        bProfessor.setText("Professor");
        bProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProfessorActionPerformed(evt);
            }
        });

        bInfo.setText("Informações");
        bInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(bInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMateria)
                    .addComponent(labelCurso)
                    .addComponent(labelDep)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bAlunos)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxDep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDep, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAlunos)
                    .addComponent(bInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(bProfessor)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDepActionPerformed
        try{
            String cod = String.valueOf(comboBoxDep.getSelectedItem());
            labelDep.setText(uniPrincipal.getDepartamento(cod).getNome());
            this.depPrincipal = uniPrincipal.getDepartamento(cod);

            comboBoxCurso.removeAllItems();
            comboBoxCurso.addItem("Curso");
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
            textMateria.setText("");
            
            ArrayList<Curso> cursoList = this.depPrincipal.getCursoList();
            for(int i = 0; i < cursoList.size(); i++){
                    comboBoxCurso.addItem(cursoList.get(i).getCodCurso());
            }
        }
        catch(NullPointerException nullPointerException){
            labelDep.setText("Departamento");
            this.depPrincipal = null;
            comboBoxCurso.removeAllItems();
            comboBoxCurso.addItem("Curso");
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
            textMateria.setText("");
            
        }
    }//GEN-LAST:event_comboBoxDepActionPerformed

    private void comboBoxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCursoActionPerformed
        try{     
            String cod = String.valueOf(comboBoxCurso.getSelectedItem());
            labelCurso.setText(depPrincipal.getCurso(cod).getNome());
            this.cursoPrincipal = depPrincipal.getCurso(cod);
            
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
            textMateria.setText("");
            
            ArrayList<Materia> matList = this.cursoPrincipal.getMatList();
            for(int i = 0; i < matList.size(); i++){
                    comboBoxMateria.addItem(matList.get(i).getCodMateria());
            }            
            
       }
       catch(NullPointerException nullPointerException){
            labelCurso.setText("Nome");
            this.cursoPrincipal = null;
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
            textMateria.setText("");
       }
    }//GEN-LAST:event_comboBoxCursoActionPerformed

    private void comboBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMateriaActionPerformed
        String nomeProfessor = "";
        try{     
            String cod = String.valueOf(comboBoxMateria.getSelectedItem());
            labelMateria.setText(cursoPrincipal.getMateria(cod).getNome());
            this.materiaPrincipal = cursoPrincipal.getMateria(cod);
        }
        catch(NullPointerException nullPointerException){
            labelMateria.setText("Nome");
            this.materiaPrincipal = null;
            textMateria.setText("");
       }
    }//GEN-LAST:event_comboBoxMateriaActionPerformed

    private void bInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfoActionPerformed
        try{  
            textMateria.setText(this.materiaPrincipal.toString() + this.materiaPrincipal.getProfessor().getNome());
        }
        catch(NullPointerException nullPointerException){
            textMateria.setText(this.materiaPrincipal.toString());
       }  
    }//GEN-LAST:event_bInfoActionPerformed

    private void bProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProfessorActionPerformed
        
        try{  
            textMateria.setText(this.materiaPrincipal.getProfessor().toString());
        }
        catch(NullPointerException nullPointerException){
            textMateria.setText("");
       } 
    }//GEN-LAST:event_bProfessorActionPerformed

    private void bAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlunosActionPerformed
        try{
            ArrayList<Aluno> alunoList = materiaPrincipal.getAlunoList();
            String alunoText = "";

            for(int i = 0; i < alunoList.size(); i++){
                alunoText = alunoText + alunoList.get(i).getNome() + "\n";
            }

            textMateria.setText(alunoText);
        }
        catch(NullPointerException nullPointerException){
            JOptionPane.showMessageDialog(null, "Não existem Alunos cadastrados", "ERRO", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bAlunosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlunos;
    private javax.swing.JButton bInfo;
    private javax.swing.JButton bProfessor;
    private javax.swing.JComboBox<String> comboBoxCurso;
    private javax.swing.JComboBox<String> comboBoxDep;
    private javax.swing.JComboBox<String> comboBoxMateria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelDep;
    private javax.swing.JLabel labelMateria;
    private javax.swing.JTextArea textMateria;
    // End of variables declaration//GEN-END:variables
}
