/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import trabalho2.Aluno;
import trabalho2.Materia;
import trabalho2.Professor;
import trabalho2.Universidade;

/**
 *
 * @author jonat
 */
public class NotasPorTurma extends javax.swing.JInternalFrame {

    /**
     * Creates new form NotasPorTurma
     */
    
    private Universidade uniPrincipal;
    private Professor profPrincipal;
    private Materia matPrincipal;
    private ArrayList<Materia> matList;
    
    public NotasPorTurma(Universidade uniPrincipal, String self) {
        initComponents();
        this.uniPrincipal = uniPrincipal;
        profPrincipal = uniPrincipal.getProfessor(self);
        matList = profPrincipal.getMatList();
        for(int i = 0; i < matList.size(); i++){
                comboBoxMat.addItem(matList.get(i).getCodMateria());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxMat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        labelMatShow = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxAluno = new javax.swing.JComboBox<>();
        labelAlunoShow = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setText("Matérias:");

        comboBoxMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMatActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        labelMatShow.setText("Nome");

        jLabel2.setText("Aluno:");

        comboBoxAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAlunoActionPerformed(evt);
            }
        });

        labelAlunoShow.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlunoShow)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelMatShow)
                        .addComponent(comboBoxMat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxAluno, 0, 178, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMatShow)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlunoShow)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMatActionPerformed
        try{
            String cod = String.valueOf(comboBoxMat.getSelectedItem());
            for(int i = 0; i < matList.size(); i++){
                if(matList.get(i).getCodMateria().equals(cod)){
                    labelMatShow.setText(matList.get(i).getNome());
                    this.matPrincipal = matList.get(i);
                }
            }

            comboBoxAluno.removeAllItems();
            comboBoxAluno.addItem("Aluno");

            
            ArrayList<Aluno> alunos = matPrincipal.getAlunoList();
            for(int i = 0; i < alunos.size(); i++){
                comboBoxAluno.addItem(alunos.get(i).getMatricula());
            }
        }
        catch(NullPointerException nullPointerException){
            labelMatShow.setText("ERRO");
        }
    }//GEN-LAST:event_comboBoxMatActionPerformed

    private void comboBoxAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAlunoActionPerformed
        try{     
            String cod = String.valueOf(comboBoxAluno.getSelectedItem());
            labelAlunoShow.setText(uniPrincipal.getAluno(cod).getNome());
            String notas = uniPrincipal.getAluno(cod).getNotaMat(matPrincipal.getCodMateria());
            textArea.setText(notas);
       }
       catch(NullPointerException nullPointerException){
            labelAlunoShow.setText("Nome");
       }
    }//GEN-LAST:event_comboBoxAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxAluno;
    private javax.swing.JComboBox<String> comboBoxMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlunoShow;
    private javax.swing.JLabel labelMatShow;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
