/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import auxiliar.Senhas;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import menu.MenuSecretaria;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class RemoveString extends javax.swing.JInternalFrame {

    /**
     * Creates new form BurcaString
     */
    private Universidade uniPrincipal;
    private Senhas infoLogin;
    private int tipo;
    private int flag = 0;
    private String info = "0";
    private String registro;
    
    
    public RemoveString(Universidade uniPrincipal, Senhas infoLogin, int tipo) {
        initComponents();
        this.tipo = tipo;
        if(tipo == 3)
            jLabel1.setText("Matricula:");
        else if(tipo == 4 || tipo == 5 || tipo == 6){
            jLabel1.setText("Codigo:");
        }
            
        this.uniPrincipal = uniPrincipal;
        this.infoLogin = infoLogin;
    }
    
    public int setFlag(String infoS, int flagS){
            if(!infoS.equals("Não encontrado")){
                flagS = 1;
            }
        return flagS;
    }
    
    public void membroApagado(int flagS){
           if(flag == 1){
                JOptionPane.showMessageDialog(null, "Membro " + registro + " Apagado", "Apagado", INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Membro " + registro + " não existe", "ERRO", ERROR_MESSAGE);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textBusca = new javax.swing.JTextField();
        bConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bApagar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Registro:");

        bConfirmar.setText("Confirmar");
        bConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmarActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        bApagar.setText("Apagar");
        bApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bApagar))
                    .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textBusca)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConfirmar)
                    .addComponent(bApagar))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmarActionPerformed
        info = "0";
        flag = 0;
        registro = textBusca.getText();
        if(tipo == 1){
            info = uniPrincipal.getSecretarioUniversidade(registro);
            flag = setFlag(info, flag);
        }
        else if(tipo == 2){
            info = uniPrincipal.getProfessorUniversidade(registro);
            flag = setFlag(info, flag);
        }
        else if(tipo == 3){
            info = uniPrincipal.getAlunoUniversidade(registro);
            flag = setFlag(info, flag);
        }
        else if(tipo == 4){
            info = (uniPrincipal.getDepartamento(textBusca.getText()).toString());
        }
        else if(tipo == 5){
            info = (uniPrincipal.getCursoUniversidade(textBusca.getText()));
        }
        else if(tipo == 6){
            info = (uniPrincipal.getMateriaUniversidade(textBusca.getText()));
        }
        jTextArea1.setText(info);
    }//GEN-LAST:event_bConfirmarActionPerformed

    private void bApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApagarActionPerformed
        if(tipo == 1){
            if(flag == 1){
                uniPrincipal.removeSecretarioUniversidade(registro);
                infoLogin.removeLogin(registro);
            }
            membroApagado(flag);
        }
        else if(tipo == 2){
            if(flag == 1){
                String dep = uniPrincipal.getProfessor(registro).getDepartamento();
                uniPrincipal.getDepartamento(dep).removeProfessor(registro);
                uniPrincipal.removeProfessorUniversidade(registro);
                infoLogin.removeLogin(registro);
            }
        }
        else if(tipo == 3){
            if(flag == 1){
                String cod = uniPrincipal.getAluno(registro).getCurso();
                uniPrincipal.getCurso(cod).removeAluno(registro);
                uniPrincipal.removeAlunoUniversidade(registro);
                infoLogin.removeLogin(registro);
            }
        }
        else if(tipo == 4){
            info = (uniPrincipal.getDepartamento(textBusca.getText()).toString());
        }
        else if(tipo == 5){
            info = (uniPrincipal.getCursoUniversidade(textBusca.getText()));
        }
        else if(tipo == 6){
            info = (uniPrincipal.getMateriaUniversidade(textBusca.getText()));
        }
    }//GEN-LAST:event_bApagarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApagar;
    private javax.swing.JButton bConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textBusca;
    // End of variables declaration//GEN-END:variables
}
