/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import menu.MenuSecretaria;
import trabalho2.Curso;
import trabalho2.Departamento;
import trabalho2.Materia;
import java.lang.NullPointerException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import trabalho2.Professor;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class SetProfessorMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarMateria
     */

    private Departamento depPrincipal;
    private Curso cursoPrincipal;
    private Materia materiaPrincipal;
    private Universidade uniPrincipal;
    
    public SetProfessorMateria() {
        initComponents();
        uniPrincipal = MenuSecretaria.getUniversidade();
        ArrayList<Departamento> depList = MenuSecretaria.getUniversidade().getDepList();
        for(int i = 0; i < depList.size(); i++){
                comboBoxDep.addItem(depList.get(i).getCodDep());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textRegistro = new javax.swing.JTextField();
        bSalvar = new javax.swing.JButton();
        comboBoxDep = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        labelDepShow = new javax.swing.JLabel();
        comboBoxCurso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        labelCursoShow = new javax.swing.JLabel();
        comboBoxMateria = new javax.swing.JComboBox<>();
        labelMateriaShow = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel3.setText("Registro:");

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        comboBoxDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Departamento" }));
        comboBoxDep.setToolTipText("");
        comboBoxDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDepActionPerformed(evt);
            }
        });

        jLabel1.setText("Departamento:");

        labelDepShow.setFont(new java.awt.Font("URW Gothic L", 1, 14)); // NOI18N
        labelDepShow.setText("Nome");
        labelDepShow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Curso" }));
        comboBoxCurso.setToolTipText("");
        comboBoxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCursoActionPerformed(evt);
            }
        });

        jLabel2.setText("Curso:");

        labelCursoShow.setFont(new java.awt.Font("URW Gothic L", 1, 14)); // NOI18N
        labelCursoShow.setText("Nome");
        labelCursoShow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        comboBoxMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matéria" }));
        comboBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMateriaActionPerformed(evt);
            }
        });

        labelMateriaShow.setFont(new java.awt.Font("URW Gothic L", 1, 14)); // NOI18N
        labelMateriaShow.setText("Nome");

        jLabel5.setText("Matéria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCursoShow, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDepShow, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMateriaShow)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bSalvar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDepShow, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCursoShow, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMateriaShow)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bSalvar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        try{
            Professor professor = uniPrincipal.getProfessor(textRegistro.getText());
            professor.getNome();
            materiaPrincipal.setProfTitular(professor);
            professor.novaMateriaLeciona(materiaPrincipal);
            JOptionPane.showMessageDialog(null, "Professor cadastrado na Matéria", "Salvo", INFORMATION_MESSAGE);
        }
        catch(NullPointerException nullPointerException){
            JOptionPane.showMessageDialog(null, "Professor não encontrado", "ERRO", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bSalvarActionPerformed

    private void comboBoxDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDepActionPerformed
        try{
            String cod = String.valueOf(comboBoxDep.getSelectedItem());
            labelDepShow.setText(MenuSecretaria.getUniversidade().getDepartamento(cod).getNome());
            this.depPrincipal = MenuSecretaria.getUniversidade().getDepartamento(cod);
            
            comboBoxCurso.removeAllItems();
            comboBoxCurso.addItem("Curso");

            
            ArrayList<Curso> cursoList = this.depPrincipal.getCursoList();
            for(int i = 0; i < cursoList.size(); i++){
                    comboBoxCurso.addItem(cursoList.get(i).getCodCurso());
            }
        }
        catch(NullPointerException nullPointerException){
            labelDepShow.setText("Nome");
            this.depPrincipal = null;
            comboBoxCurso.removeAllItems();
            comboBoxCurso.addItem("Curso");
        }
    }//GEN-LAST:event_comboBoxDepActionPerformed

    private void comboBoxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCursoActionPerformed
        try{
            String cod = String.valueOf(comboBoxCurso.getSelectedItem());
            labelCursoShow.setText(depPrincipal.getCurso(cod).getNome());
            this.cursoPrincipal = depPrincipal.getCurso(cod);
            
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");

            
            ArrayList<Materia> matList = this.cursoPrincipal.getMatList();
            for(int i = 0; i < matList.size(); i++){
                    comboBoxMateria.addItem(matList.get(i).getCodMateria());
            }
        }
        catch(NullPointerException nullPointerException){
            labelCursoShow.setText("Nome");
            this.cursoPrincipal = null;
            comboBoxMateria.removeAllItems();
            comboBoxMateria.addItem("Materia");
        }    
    }//GEN-LAST:event_comboBoxCursoActionPerformed

    private void comboBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMateriaActionPerformed
        try{     
            String cod = String.valueOf(comboBoxMateria.getSelectedItem());
            labelMateriaShow.setText(cursoPrincipal.getMateria(cod).getNome());
            this.materiaPrincipal = cursoPrincipal.getMateria(cod);
       }
       catch(NullPointerException nullPointerException){
            labelMateriaShow.setText("Nome");
            this.materiaPrincipal = null;
       }
    }//GEN-LAST:event_comboBoxMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSalvar;
    private javax.swing.JComboBox<String> comboBoxCurso;
    private javax.swing.JComboBox<String> comboBoxDep;
    private javax.swing.JComboBox<String> comboBoxMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelCursoShow;
    private javax.swing.JLabel labelDepShow;
    private javax.swing.JLabel labelMateriaShow;
    private javax.swing.JTextField textRegistro;
    // End of variables declaration//GEN-END:variables
}
