/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import auxiliar.Matricula;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import trabalho2.Curso;
import trabalho2.Materia;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class SolicitacaoMatricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form SolicitacaoMatricula
     */
    
    private Universidade uniPrincipal;
    private String self; 
    private String codCurso;
    private Curso cursoPrincipal;
    private Materia matPrincipal;
    
    public SolicitacaoMatricula(Universidade uniPrincipal, String self, String codCurso) {
        initComponents();
        this.uniPrincipal = uniPrincipal;
        this.self = self;
        cursoPrincipal = uniPrincipal.getCurso(codCurso);
        ArrayList<Materia> matList = cursoPrincipal.getMatList();
        for(int i = 0; i < matList.size(); i++){
                comboBoxMat.addItem(matList.get(i).getCodMateria());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxMat = new javax.swing.JComboBox<>();
        labelMatShow = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        bSolicitar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Curso");

        jLabel2.setText("Materia:");

        comboBoxMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMatActionPerformed(evt);
            }
        });

        labelMatShow.setText("Nome");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        bSolicitar.setText("Solicitar Matricula");
        bSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSolicitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMatShow)
                    .addComponent(comboBoxMat, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSolicitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMatShow)
                .addGap(23, 23, 23)
                .addComponent(bSolicitar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSolicitarActionPerformed
        new Matricula(matPrincipal, uniPrincipal.getAluno(self), uniPrincipal);
        JOptionPane.showMessageDialog(null, "Matricula Solicitada", "Salvo", INFORMATION_MESSAGE);
    }//GEN-LAST:event_bSolicitarActionPerformed

    private void comboBoxMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMatActionPerformed
        try{     
            String cod = String.valueOf(comboBoxMat.getSelectedItem());
            labelMatShow.setText(cursoPrincipal.getMateria(cod).getNome());
            this.matPrincipal = cursoPrincipal.getMateria(cod);
            textArea.setText(this.matPrincipal.toString());
            
       }
       catch(NullPointerException nullPointerException){
            labelMatShow.setText("Nome");
            this.matPrincipal = null;
       }
    }//GEN-LAST:event_comboBoxMatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSolicitar;
    private javax.swing.JComboBox<String> comboBoxMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMatShow;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
