/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import auxiliar.Matricula;
import java.util.ArrayList;
import trabalho2.Universidade;

/**
 *
 * @author delatorre
 */
public class SolicitacaoShow extends javax.swing.JInternalFrame {

    /**
     * Creates new form SolicitacaoShow
     */
    
    private Universidade uniPrincipal;
    private String self;
    private ArrayList<Matricula> matList;
    
    public SolicitacaoShow(Universidade uniPrincipal, String self) {
        initComponents();
        this.uniPrincipal = uniPrincipal;
        this.self = self;
        this.matList = this.uniPrincipal.getAluno(self).getMatriculas();
        for(int i = 0; i < matList.size(); i++){
            comboBoxMat.addItem(matList.get(i).getMateria().getCodMateria());
        }
        
    }
    
    public void getInfo(String cod) throws NullPointerException{
        for(int i = 0; i < matList.size(); i++){
            if(matList.get(i).getMateria().getCodMateria().equals(cod)){    
                labelMatShow.setText(matList.get(i).getMateria().getNome());
                textArea.setText(matList.get(i).toString());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxMat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        labelMatShow = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Materia:");

        comboBoxMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMatActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        labelMatShow.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMatShow)
                    .addComponent(comboBoxMat, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(labelMatShow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMatActionPerformed
        try{     
            String cod = String.valueOf(comboBoxMat.getSelectedItem());
            getInfo(cod);
            
       }
       catch(NullPointerException nullPointerException){
            labelMatShow.setText("Nome");
       }
    }//GEN-LAST:event_comboBoxMatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMatShow;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
