/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import Dados.EntradaDados;
import auxiliar.Senhas;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import trabalho2.Universidade;
import view.AlteraInfo;
import view.Cadastros.CadastroProfessor;
import view.Cadastros.CadastroSecretaria;
import view.BurcaString;
import view.MateriaInfo;
import view.Cadastros.CadastroAluno;
import view.Cadastros.CadastroCurso;
import view.Cadastros.CadastroDepartamento;
import view.Cadastros.CadastroMateria;
import view.Cadastros.DadosUniversidade;
import view.CursoInfo;
import view.DepInfo;
import view.NotasPorTurma;
import view.RegistraNotas;
import view.RemoveString;
import view.SetProfessorMateria;

/**
 *
 * @author delatorre
 */
public class MenuProfessor extends javax.swing.JFrame {

    /**
     * Creates new form MenuSecretaria
     */
    private static Universidade uniPrincipal;
    private static Senhas infoLogin;
    private static String self;
    
    public MenuProfessor() {
        initComponents();
    }
    
    public static void setClasses(Universidade uniPrincipalS, Senhas infoLoginS, String selfS){
        uniPrincipal = uniPrincipalS;
        infoLogin = infoLoginS;
        self = selfS;
    }
    
    public static Universidade getUniversidade(){
        return uniPrincipal;
    }
    
    public static Senhas getSenhas(){
        return infoLogin;
    }
    
    public void removeMembro(int nivel){
        RemoveString remove = new RemoveString(uniPrincipal, infoLogin, nivel);
        desktop1.add(remove);
        remove.setVisible(true);
    }
    
    public void buscaString(int id){
        BurcaString busca = new BurcaString(uniPrincipal, id);
        desktop1.add(busca);
        busca.setVisible(true);
    }
    
    public void buscaString(int id, String self){
        if(!self.equals("adm")){
            BurcaString busca = new BurcaString(uniPrincipal, id, self);
            desktop1.add(busca);
            busca.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Loguin como Administrador", "ERRO", ERROR_MESSAGE);
        }
    }
    
    public void alteraInfo(String label, String self){
        AlteraInfo alterar = new AlteraInfo(uniPrincipal, infoLogin, label, self, 2);
        desktop1.add(alterar);
        alterar.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        desktop1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuMembros = new javax.swing.JMenu();
        buscarAluno = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opInfoDep = new javax.swing.JMenuItem();
        opBuscaCurso = new javax.swing.JMenuItem();
        opBuscaMateria = new javax.swing.JMenuItem();
        opNotas = new javax.swing.JMenu();
        registraNotas = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuConfig = new javax.swing.JMenu();
        opMinhasInfo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        alterarEmail = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        opSair = new javax.swing.JMenuItem();
        opSalvar = new javax.swing.JMenuItem();
        opSalvarSair = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktop1Layout = new javax.swing.GroupLayout(desktop1);
        desktop1.setLayout(desktop1Layout);
        desktop1Layout.setHorizontalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        desktop1Layout.setVerticalGroup(
            desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jMenu2.setText("Universidade");

        jMenuItem2.setText("Dados da Universidade");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        menuMembros.setText("Membros");

        buscarAluno.setText("Aluno(a)");
        buscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlunoActionPerformed(evt);
            }
        });
        menuMembros.add(buscarAluno);

        jMenuBar1.add(menuMembros);

        jMenu3.setText("Buscar");

        opInfoDep.setText("Departamento");
        opInfoDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opInfoDepActionPerformed(evt);
            }
        });
        jMenu3.add(opInfoDep);

        opBuscaCurso.setText("Curso");
        opBuscaCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opBuscaCursoActionPerformed(evt);
            }
        });
        jMenu3.add(opBuscaCurso);

        opBuscaMateria.setText("Materia");
        opBuscaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opBuscaMateriaActionPerformed(evt);
            }
        });
        jMenu3.add(opBuscaMateria);

        jMenuBar1.add(jMenu3);

        opNotas.setText("Notas");

        registraNotas.setText("Registrar Notas");
        registraNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraNotasActionPerformed(evt);
            }
        });
        opNotas.add(registraNotas);

        jMenuItem4.setText("Notas por Turma");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        opNotas.add(jMenuItem4);

        jMenuBar1.add(opNotas);

        menuConfig.setText("Configurações");

        opMinhasInfo.setText("Minhas Informações");
        opMinhasInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMinhasInfoActionPerformed(evt);
            }
        });
        menuConfig.add(opMinhasInfo);

        jMenu1.setText("Alterar Minhas Informações");

        alterarEmail.setText("Alterar Email");
        alterarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEmailActionPerformed(evt);
            }
        });
        jMenu1.add(alterarEmail);

        jMenuItem3.setText("Alterar Numero");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem5.setText("Alterar Senha");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        menuConfig.add(jMenu1);

        jMenuBar1.add(menuConfig);

        menuSair.setText("Sair");

        opSair.setText("Sair");
        opSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSairActionPerformed(evt);
            }
        });
        menuSair.add(opSair);

        opSalvar.setText("Salvar");
        opSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalvarActionPerformed(evt);
            }
        });
        menuSair.add(opSalvar);

        opSalvarSair.setText("Salvar e sair");
        opSalvarSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalvarSairActionPerformed(evt);
            }
        });
        menuSair.add(opSalvarSair);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opBuscaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opBuscaCursoActionPerformed
        CursoInfo cursoInfo = new CursoInfo(uniPrincipal);
        desktop1.add(cursoInfo);
        cursoInfo.setVisible(true);
    }//GEN-LAST:event_opBuscaCursoActionPerformed

    private void opBuscaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opBuscaMateriaActionPerformed
        MateriaInfo busca = new MateriaInfo(uniPrincipal);
        desktop1.add(busca);
        busca.setVisible(true);
    }//GEN-LAST:event_opBuscaMateriaActionPerformed

    private void opSalvarSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalvarSairActionPerformed
        EntradaDados.escreveDados(uniPrincipal);
        System.exit(0);
    }//GEN-LAST:event_opSalvarSairActionPerformed

    private void opSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opSairActionPerformed

    private void opSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalvarActionPerformed
        EntradaDados.escreveDados(uniPrincipal);
        EntradaDados.closeOutputFile();
    }//GEN-LAST:event_opSalvarActionPerformed

    private void buscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlunoActionPerformed
        buscaString(3);
    }//GEN-LAST:event_buscarAlunoActionPerformed

    private void opInfoDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opInfoDepActionPerformed
        DepInfo depInfo = new DepInfo(uniPrincipal);
        desktop1.add(depInfo);
        depInfo.setVisible(true);
    }//GEN-LAST:event_opInfoDepActionPerformed

    private void opMinhasInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMinhasInfoActionPerformed
        buscaString(2, self);
    }//GEN-LAST:event_opMinhasInfoActionPerformed

    private void alterarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEmailActionPerformed
        alteraInfo("Email", self);
    }//GEN-LAST:event_alterarEmailActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        alteraInfo("Numero", self);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        alteraInfo("Nova Senha", self);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void registraNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraNotasActionPerformed
        RegistraNotas registraNotas = new RegistraNotas(uniPrincipal, self);
        desktop1.add(registraNotas);
        registraNotas.setVisible(true);
    }//GEN-LAST:event_registraNotasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        NotasPorTurma notasPorTurma = new NotasPorTurma(uniPrincipal, self);
        desktop1.add(notasPorTurma);
        notasPorTurma.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DadosUniversidade dadosUniversidade = new DadosUniversidade(uniPrincipal);
        desktop1.add(dadosUniversidade);
        dadosUniversidade.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarEmail;
    private javax.swing.JMenuItem buscarAluno;
    private javax.swing.JDesktopPane desktop1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenu menuMembros;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem opBuscaCurso;
    private javax.swing.JMenuItem opBuscaMateria;
    private javax.swing.JMenuItem opInfoDep;
    private javax.swing.JMenuItem opMinhasInfo;
    private javax.swing.JMenu opNotas;
    private javax.swing.JMenuItem opSair;
    private javax.swing.JMenuItem opSalvar;
    private javax.swing.JMenuItem opSalvarSair;
    private javax.swing.JMenuItem registraNotas;
    // End of variables declaration//GEN-END:variables
}
